name: Lawrence Shockey
favicon: null
layout_spectrum: 0.9175206474028528
typography_spectrum: 0.9129963503219187
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5411759598646313
  lightness: 0.5140601235907525
  saturation: 0.5306872734799981
  rhythmicContrast: 0.3996310709044337
purpose: []
